triangle(pol_12).
triangle(pol_17).
triangle(pol_2).
triangle(pol_7).
not_triangle(pol_22).
not_triangle(pol_27).
not_triangle(pol_32).
not_triangle(pol_37).
not_triangle(pol_42).
not_triangle(pol_47).
not_triangle(pol_52).
not_triangle(pol_57).
not_triangle(pol_62).
not_triangle(pol_67).
not_triangle(pol_72).
not_triangle(pol_77).
quadrangle(pol_22).
quadrangle(pol_27).
quadrangle(pol_32).
quadrangle(pol_37).
not_quadrangle(pol_12).
not_quadrangle(pol_17).
not_quadrangle(pol_2).
not_quadrangle(pol_42).
not_quadrangle(pol_47).
not_quadrangle(pol_52).
not_quadrangle(pol_57).
not_quadrangle(pol_62).
not_quadrangle(pol_67).
not_quadrangle(pol_7).
not_quadrangle(pol_72).
not_quadrangle(pol_77).
pentagon(pol_42).
pentagon(pol_47).
pentagon(pol_52).
pentagon(pol_57).
not_pentagon(pol_12).
not_pentagon(pol_17).
not_pentagon(pol_2).
not_pentagon(pol_22).
not_pentagon(pol_27).
not_pentagon(pol_32).
not_pentagon(pol_37).
not_pentagon(pol_62).
not_pentagon(pol_67).
not_pentagon(pol_7).
not_pentagon(pol_72).
not_pentagon(pol_77).
hexagon(pol_62).
hexagon(pol_67).
hexagon(pol_72).
hexagon(pol_77).
not_hexagon(pol_12).
not_hexagon(pol_17).
not_hexagon(pol_2).
not_hexagon(pol_22).
not_hexagon(pol_27).
not_hexagon(pol_32).
not_hexagon(pol_37).
not_hexagon(pol_42).
not_hexagon(pol_47).
not_hexagon(pol_52).
not_hexagon(pol_57).
not_hexagon(pol_7).
