triangle(pol_13).
triangle(pol_18).
triangle(pol_3).
triangle(pol_8).
not_triangle(pol_23).
not_triangle(pol_28).
not_triangle(pol_33).
not_triangle(pol_38).
not_triangle(pol_43).
not_triangle(pol_48).
not_triangle(pol_53).
not_triangle(pol_58).
not_triangle(pol_63).
not_triangle(pol_68).
not_triangle(pol_73).
not_triangle(pol_78).
quadrangle(pol_23).
quadrangle(pol_28).
quadrangle(pol_33).
quadrangle(pol_38).
not_quadrangle(pol_13).
not_quadrangle(pol_18).
not_quadrangle(pol_3).
not_quadrangle(pol_43).
not_quadrangle(pol_48).
not_quadrangle(pol_53).
not_quadrangle(pol_58).
not_quadrangle(pol_63).
not_quadrangle(pol_68).
not_quadrangle(pol_73).
not_quadrangle(pol_78).
not_quadrangle(pol_8).
pentagon(pol_43).
pentagon(pol_48).
pentagon(pol_53).
pentagon(pol_58).
not_pentagon(pol_13).
not_pentagon(pol_18).
not_pentagon(pol_23).
not_pentagon(pol_28).
not_pentagon(pol_3).
not_pentagon(pol_33).
not_pentagon(pol_38).
not_pentagon(pol_63).
not_pentagon(pol_68).
not_pentagon(pol_73).
not_pentagon(pol_78).
not_pentagon(pol_8).
hexagon(pol_63).
hexagon(pol_68).
hexagon(pol_73).
hexagon(pol_78).
not_hexagon(pol_13).
not_hexagon(pol_18).
not_hexagon(pol_23).
not_hexagon(pol_28).
not_hexagon(pol_3).
not_hexagon(pol_33).
not_hexagon(pol_38).
not_hexagon(pol_43).
not_hexagon(pol_48).
not_hexagon(pol_53).
not_hexagon(pol_58).
not_hexagon(pol_8).
