triangle(pol_10).
triangle(pol_12).
triangle(pol_13).
triangle(pol_14).
triangle(pol_15).
triangle(pol_17).
triangle(pol_18).
triangle(pol_19).
triangle(pol_2).
triangle(pol_20).
triangle(pol_3).
triangle(pol_4).
triangle(pol_5).
triangle(pol_7).
triangle(pol_8).
triangle(pol_9).
not_triangle(pol_22).
not_triangle(pol_23).
not_triangle(pol_24).
not_triangle(pol_25).
not_triangle(pol_27).
not_triangle(pol_28).
not_triangle(pol_29).
not_triangle(pol_30).
not_triangle(pol_32).
not_triangle(pol_33).
not_triangle(pol_34).
not_triangle(pol_35).
not_triangle(pol_37).
not_triangle(pol_38).
not_triangle(pol_39).
not_triangle(pol_40).
not_triangle(pol_42).
not_triangle(pol_43).
not_triangle(pol_44).
not_triangle(pol_45).
not_triangle(pol_47).
not_triangle(pol_48).
not_triangle(pol_49).
not_triangle(pol_50).
not_triangle(pol_52).
not_triangle(pol_53).
not_triangle(pol_54).
not_triangle(pol_55).
not_triangle(pol_57).
not_triangle(pol_58).
not_triangle(pol_59).
not_triangle(pol_60).
not_triangle(pol_62).
not_triangle(pol_63).
not_triangle(pol_64).
not_triangle(pol_65).
not_triangle(pol_67).
not_triangle(pol_68).
not_triangle(pol_69).
not_triangle(pol_70).
not_triangle(pol_72).
not_triangle(pol_73).
not_triangle(pol_74).
not_triangle(pol_75).
not_triangle(pol_77).
not_triangle(pol_78).
not_triangle(pol_79).
not_triangle(pol_80).
quadrangle(pol_22).
quadrangle(pol_23).
quadrangle(pol_24).
quadrangle(pol_25).
quadrangle(pol_27).
quadrangle(pol_28).
quadrangle(pol_29).
quadrangle(pol_30).
quadrangle(pol_32).
quadrangle(pol_33).
quadrangle(pol_34).
quadrangle(pol_35).
quadrangle(pol_37).
quadrangle(pol_38).
quadrangle(pol_39).
quadrangle(pol_40).
not_quadrangle(pol_10).
not_quadrangle(pol_12).
not_quadrangle(pol_13).
not_quadrangle(pol_14).
not_quadrangle(pol_15).
not_quadrangle(pol_17).
not_quadrangle(pol_18).
not_quadrangle(pol_19).
not_quadrangle(pol_2).
not_quadrangle(pol_20).
not_quadrangle(pol_3).
not_quadrangle(pol_4).
not_quadrangle(pol_42).
not_quadrangle(pol_43).
not_quadrangle(pol_44).
not_quadrangle(pol_45).
not_quadrangle(pol_47).
not_quadrangle(pol_48).
not_quadrangle(pol_49).
not_quadrangle(pol_5).
not_quadrangle(pol_50).
not_quadrangle(pol_52).
not_quadrangle(pol_53).
not_quadrangle(pol_54).
not_quadrangle(pol_55).
not_quadrangle(pol_57).
not_quadrangle(pol_58).
not_quadrangle(pol_59).
not_quadrangle(pol_60).
not_quadrangle(pol_62).
not_quadrangle(pol_63).
not_quadrangle(pol_64).
not_quadrangle(pol_65).
not_quadrangle(pol_67).
not_quadrangle(pol_68).
not_quadrangle(pol_69).
not_quadrangle(pol_7).
not_quadrangle(pol_70).
not_quadrangle(pol_72).
not_quadrangle(pol_73).
not_quadrangle(pol_74).
not_quadrangle(pol_75).
not_quadrangle(pol_77).
not_quadrangle(pol_78).
not_quadrangle(pol_79).
not_quadrangle(pol_8).
not_quadrangle(pol_80).
not_quadrangle(pol_9).
pentagon(pol_42).
pentagon(pol_43).
pentagon(pol_44).
pentagon(pol_45).
pentagon(pol_47).
pentagon(pol_48).
pentagon(pol_49).
pentagon(pol_50).
pentagon(pol_52).
pentagon(pol_53).
pentagon(pol_54).
pentagon(pol_55).
pentagon(pol_57).
pentagon(pol_58).
pentagon(pol_59).
pentagon(pol_60).
not_pentagon(pol_10).
not_pentagon(pol_12).
not_pentagon(pol_13).
not_pentagon(pol_14).
not_pentagon(pol_15).
not_pentagon(pol_17).
not_pentagon(pol_18).
not_pentagon(pol_19).
not_pentagon(pol_2).
not_pentagon(pol_20).
not_pentagon(pol_22).
not_pentagon(pol_23).
not_pentagon(pol_24).
not_pentagon(pol_25).
not_pentagon(pol_27).
not_pentagon(pol_28).
not_pentagon(pol_29).
not_pentagon(pol_3).
not_pentagon(pol_30).
not_pentagon(pol_32).
not_pentagon(pol_33).
not_pentagon(pol_34).
not_pentagon(pol_35).
not_pentagon(pol_37).
not_pentagon(pol_38).
not_pentagon(pol_39).
not_pentagon(pol_4).
not_pentagon(pol_40).
not_pentagon(pol_5).
not_pentagon(pol_62).
not_pentagon(pol_63).
not_pentagon(pol_64).
not_pentagon(pol_65).
not_pentagon(pol_67).
not_pentagon(pol_68).
not_pentagon(pol_69).
not_pentagon(pol_7).
not_pentagon(pol_70).
not_pentagon(pol_72).
not_pentagon(pol_73).
not_pentagon(pol_74).
not_pentagon(pol_75).
not_pentagon(pol_77).
not_pentagon(pol_78).
not_pentagon(pol_79).
not_pentagon(pol_8).
not_pentagon(pol_80).
not_pentagon(pol_9).
hexagon(pol_62).
hexagon(pol_63).
hexagon(pol_64).
hexagon(pol_65).
hexagon(pol_67).
hexagon(pol_68).
hexagon(pol_69).
hexagon(pol_70).
hexagon(pol_72).
hexagon(pol_73).
hexagon(pol_74).
hexagon(pol_75).
hexagon(pol_77).
hexagon(pol_78).
hexagon(pol_79).
hexagon(pol_80).
not_hexagon(pol_10).
not_hexagon(pol_12).
not_hexagon(pol_13).
not_hexagon(pol_14).
not_hexagon(pol_15).
not_hexagon(pol_17).
not_hexagon(pol_18).
not_hexagon(pol_19).
not_hexagon(pol_2).
not_hexagon(pol_20).
not_hexagon(pol_22).
not_hexagon(pol_23).
not_hexagon(pol_24).
not_hexagon(pol_25).
not_hexagon(pol_27).
not_hexagon(pol_28).
not_hexagon(pol_29).
not_hexagon(pol_3).
not_hexagon(pol_30).
not_hexagon(pol_32).
not_hexagon(pol_33).
not_hexagon(pol_34).
not_hexagon(pol_35).
not_hexagon(pol_37).
not_hexagon(pol_38).
not_hexagon(pol_39).
not_hexagon(pol_4).
not_hexagon(pol_40).
not_hexagon(pol_42).
not_hexagon(pol_43).
not_hexagon(pol_44).
not_hexagon(pol_45).
not_hexagon(pol_47).
not_hexagon(pol_48).
not_hexagon(pol_49).
not_hexagon(pol_5).
not_hexagon(pol_50).
not_hexagon(pol_52).
not_hexagon(pol_53).
not_hexagon(pol_54).
not_hexagon(pol_55).
not_hexagon(pol_57).
not_hexagon(pol_58).
not_hexagon(pol_59).
not_hexagon(pol_60).
not_hexagon(pol_7).
not_hexagon(pol_8).
not_hexagon(pol_9).
