episode(triangle,
	[
	 [triangle, pol_1],
	 [triangle, pol_11],
	 [triangle, pol_12],
	 [triangle, pol_13],
	 [triangle, pol_14],
	 [triangle, pol_16],
	 [triangle, pol_17],
	 [triangle, pol_18],
	 [triangle, pol_19],
	 [triangle, pol_2],
	 [triangle, pol_3],
	 [triangle, pol_4],
	 [triangle, pol_6],
	 [triangle, pol_7],
	 [triangle, pol_8],
	 [triangle, pol_9]
	],
	[
	 [triangle, pol_21],
	 [triangle, pol_22],
	 [triangle, pol_23],
	 [triangle, pol_24],
	 [triangle, pol_26],
	 [triangle, pol_27],
	 [triangle, pol_28],
	 [triangle, pol_29],
	 [triangle, pol_31],
	 [triangle, pol_32],
	 [triangle, pol_33],
	 [triangle, pol_34],
	 [triangle, pol_36],
	 [triangle, pol_37],
	 [triangle, pol_38],
	 [triangle, pol_39],
	 [triangle, pol_41],
	 [triangle, pol_42],
	 [triangle, pol_43],
	 [triangle, pol_44],
	 [triangle, pol_46],
	 [triangle, pol_47],
	 [triangle, pol_48],
	 [triangle, pol_49],
	 [triangle, pol_51],
	 [triangle, pol_52],
	 [triangle, pol_53],
	 [triangle, pol_54],
	 [triangle, pol_56],
	 [triangle, pol_57],
	 [triangle, pol_58],
	 [triangle, pol_59],
	 [triangle, pol_61],
	 [triangle, pol_62],
	 [triangle, pol_63],
	 [triangle, pol_64],
	 [triangle, pol_66],
	 [triangle, pol_67],
	 [triangle, pol_68],
	 [triangle, pol_69],
	 [triangle, pol_71],
	 [triangle, pol_72],
	 [triangle, pol_73],
	 [triangle, pol_74],
	 [triangle, pol_76],
	 [triangle, pol_77],
	 [triangle, pol_78],
	 [triangle, pol_79]
	]
       ).

episode(quadrangle,
	[
	 [quadrangle, pol_21],
	 [quadrangle, pol_22],
	 [quadrangle, pol_23],
	 [quadrangle, pol_24],
	 [quadrangle, pol_26],
	 [quadrangle, pol_27],
	 [quadrangle, pol_28],
	 [quadrangle, pol_29],
	 [quadrangle, pol_31],
	 [quadrangle, pol_32],
	 [quadrangle, pol_33],
	 [quadrangle, pol_34],
	 [quadrangle, pol_36],
	 [quadrangle, pol_37],
	 [quadrangle, pol_38],
	 [quadrangle, pol_39]
	],
	[
	 [quadrangle, pol_1],
	 [quadrangle, pol_11],
	 [quadrangle, pol_12],
	 [quadrangle, pol_13],
	 [quadrangle, pol_14],
	 [quadrangle, pol_16],
	 [quadrangle, pol_17],
	 [quadrangle, pol_18],
	 [quadrangle, pol_19],
	 [quadrangle, pol_2],
	 [quadrangle, pol_3],
	 [quadrangle, pol_4],
	 [quadrangle, pol_41],
	 [quadrangle, pol_42],
	 [quadrangle, pol_43],
	 [quadrangle, pol_44],
	 [quadrangle, pol_46],
	 [quadrangle, pol_47],
	 [quadrangle, pol_48],
	 [quadrangle, pol_49],
	 [quadrangle, pol_51],
	 [quadrangle, pol_52],
	 [quadrangle, pol_53],
	 [quadrangle, pol_54],
	 [quadrangle, pol_56],
	 [quadrangle, pol_57],
	 [quadrangle, pol_58],
	 [quadrangle, pol_59],
	 [quadrangle, pol_6],
	 [quadrangle, pol_61],
	 [quadrangle, pol_62],
	 [quadrangle, pol_63],
	 [quadrangle, pol_64],
	 [quadrangle, pol_66],
	 [quadrangle, pol_67],
	 [quadrangle, pol_68],
	 [quadrangle, pol_69],
	 [quadrangle, pol_7],
	 [quadrangle, pol_71],
	 [quadrangle, pol_72],
	 [quadrangle, pol_73],
	 [quadrangle, pol_74],
	 [quadrangle, pol_76],
	 [quadrangle, pol_77],
	 [quadrangle, pol_78],
	 [quadrangle, pol_79],
	 [quadrangle, pol_8],
	 [quadrangle, pol_9]
	]
       ).

episode(pentagon,
	[
	 [pentagon, pol_41],
	 [pentagon, pol_42],
	 [pentagon, pol_43],
	 [pentagon, pol_44],
	 [pentagon, pol_46],
	 [pentagon, pol_47],
	 [pentagon, pol_48],
	 [pentagon, pol_49],
	 [pentagon, pol_51],
	 [pentagon, pol_52],
	 [pentagon, pol_53],
	 [pentagon, pol_54],
	 [pentagon, pol_56],
	 [pentagon, pol_57],
	 [pentagon, pol_58],
	 [pentagon, pol_59]
	],
	[
	 [pentagon, pol_1],
	 [pentagon, pol_11],
	 [pentagon, pol_12],
	 [pentagon, pol_13],
	 [pentagon, pol_14],
	 [pentagon, pol_16],
	 [pentagon, pol_17],
	 [pentagon, pol_18],
	 [pentagon, pol_19],
	 [pentagon, pol_2],
	 [pentagon, pol_21],
	 [pentagon, pol_22],
	 [pentagon, pol_23],
	 [pentagon, pol_24],
	 [pentagon, pol_26],
	 [pentagon, pol_27],
	 [pentagon, pol_28],
	 [pentagon, pol_29],
	 [pentagon, pol_3],
	 [pentagon, pol_31],
	 [pentagon, pol_32],
	 [pentagon, pol_33],
	 [pentagon, pol_34],
	 [pentagon, pol_36],
	 [pentagon, pol_37],
	 [pentagon, pol_38],
	 [pentagon, pol_39],
	 [pentagon, pol_4],
	 [pentagon, pol_6],
	 [pentagon, pol_61],
	 [pentagon, pol_62],
	 [pentagon, pol_63],
	 [pentagon, pol_64],
	 [pentagon, pol_66],
	 [pentagon, pol_67],
	 [pentagon, pol_68],
	 [pentagon, pol_69],
	 [pentagon, pol_7],
	 [pentagon, pol_71],
	 [pentagon, pol_72],
	 [pentagon, pol_73],
	 [pentagon, pol_74],
	 [pentagon, pol_76],
	 [pentagon, pol_77],
	 [pentagon, pol_78],
	 [pentagon, pol_79],
	 [pentagon, pol_8],
	 [pentagon, pol_9]
	]
       ).

episode(hexagon,
	[
	 [hexagon, pol_61],
	 [hexagon, pol_62],
	 [hexagon, pol_63],
	 [hexagon, pol_64],
	 [hexagon, pol_66],
	 [hexagon, pol_67],
	 [hexagon, pol_68],
	 [hexagon, pol_69],
	 [hexagon, pol_71],
	 [hexagon, pol_72],
	 [hexagon, pol_73],
	 [hexagon, pol_74],
	 [hexagon, pol_76],
	 [hexagon, pol_77],
	 [hexagon, pol_78],
	 [hexagon, pol_79]
	],
	[
	 [hexagon, pol_1],
	 [hexagon, pol_11],
	 [hexagon, pol_12],
	 [hexagon, pol_13],
	 [hexagon, pol_14],
	 [hexagon, pol_16],
	 [hexagon, pol_17],
	 [hexagon, pol_18],
	 [hexagon, pol_19],
	 [hexagon, pol_2],
	 [hexagon, pol_21],
	 [hexagon, pol_22],
	 [hexagon, pol_23],
	 [hexagon, pol_24],
	 [hexagon, pol_26],
	 [hexagon, pol_27],
	 [hexagon, pol_28],
	 [hexagon, pol_29],
	 [hexagon, pol_3],
	 [hexagon, pol_31],
	 [hexagon, pol_32],
	 [hexagon, pol_33],
	 [hexagon, pol_34],
	 [hexagon, pol_36],
	 [hexagon, pol_37],
	 [hexagon, pol_38],
	 [hexagon, pol_39],
	 [hexagon, pol_4],
	 [hexagon, pol_41],
	 [hexagon, pol_42],
	 [hexagon, pol_43],
	 [hexagon, pol_44],
	 [hexagon, pol_46],
	 [hexagon, pol_47],
	 [hexagon, pol_48],
	 [hexagon, pol_49],
	 [hexagon, pol_51],
	 [hexagon, pol_52],
	 [hexagon, pol_53],
	 [hexagon, pol_54],
	 [hexagon, pol_56],
	 [hexagon, pol_57],
	 [hexagon, pol_58],
	 [hexagon, pol_59],
	 [hexagon, pol_6],
	 [hexagon, pol_7],
	 [hexagon, pol_8],
	 [hexagon, pol_9]
	]
       ).

