triangle(pol_10).
triangle(pol_15).
triangle(pol_20).
triangle(pol_5).
not_triangle(pol_25).
not_triangle(pol_30).
not_triangle(pol_35).
not_triangle(pol_40).
not_triangle(pol_45).
not_triangle(pol_50).
not_triangle(pol_55).
not_triangle(pol_60).
not_triangle(pol_65).
not_triangle(pol_70).
not_triangle(pol_75).
not_triangle(pol_80).
quadrangle(pol_25).
quadrangle(pol_30).
quadrangle(pol_35).
quadrangle(pol_40).
not_quadrangle(pol_10).
not_quadrangle(pol_15).
not_quadrangle(pol_20).
not_quadrangle(pol_45).
not_quadrangle(pol_5).
not_quadrangle(pol_50).
not_quadrangle(pol_55).
not_quadrangle(pol_60).
not_quadrangle(pol_65).
not_quadrangle(pol_70).
not_quadrangle(pol_75).
not_quadrangle(pol_80).
pentagon(pol_45).
pentagon(pol_50).
pentagon(pol_55).
pentagon(pol_60).
not_pentagon(pol_10).
not_pentagon(pol_15).
not_pentagon(pol_20).
not_pentagon(pol_25).
not_pentagon(pol_30).
not_pentagon(pol_35).
not_pentagon(pol_40).
not_pentagon(pol_5).
not_pentagon(pol_65).
not_pentagon(pol_70).
not_pentagon(pol_75).
not_pentagon(pol_80).
hexagon(pol_65).
hexagon(pol_70).
hexagon(pol_75).
hexagon(pol_80).
not_hexagon(pol_10).
not_hexagon(pol_15).
not_hexagon(pol_20).
not_hexagon(pol_25).
not_hexagon(pol_30).
not_hexagon(pol_35).
not_hexagon(pol_40).
not_hexagon(pol_45).
not_hexagon(pol_5).
not_hexagon(pol_50).
not_hexagon(pol_55).
not_hexagon(pol_60).
