triangle(pol_1).
triangle(pol_11).
triangle(pol_16).
triangle(pol_6).
not_triangle(pol_21).
not_triangle(pol_26).
not_triangle(pol_31).
not_triangle(pol_36).
not_triangle(pol_41).
not_triangle(pol_46).
not_triangle(pol_51).
not_triangle(pol_56).
not_triangle(pol_61).
not_triangle(pol_66).
not_triangle(pol_71).
not_triangle(pol_76).
quadrangle(pol_21).
quadrangle(pol_26).
quadrangle(pol_31).
quadrangle(pol_36).
not_quadrangle(pol_1).
not_quadrangle(pol_11).
not_quadrangle(pol_16).
not_quadrangle(pol_41).
not_quadrangle(pol_46).
not_quadrangle(pol_51).
not_quadrangle(pol_56).
not_quadrangle(pol_6).
not_quadrangle(pol_61).
not_quadrangle(pol_66).
not_quadrangle(pol_71).
not_quadrangle(pol_76).
pentagon(pol_41).
pentagon(pol_46).
pentagon(pol_51).
pentagon(pol_56).
not_pentagon(pol_1).
not_pentagon(pol_11).
not_pentagon(pol_16).
not_pentagon(pol_21).
not_pentagon(pol_26).
not_pentagon(pol_31).
not_pentagon(pol_36).
not_pentagon(pol_6).
not_pentagon(pol_61).
not_pentagon(pol_66).
not_pentagon(pol_71).
not_pentagon(pol_76).
hexagon(pol_61).
hexagon(pol_66).
hexagon(pol_71).
hexagon(pol_76).
not_hexagon(pol_1).
not_hexagon(pol_11).
not_hexagon(pol_16).
not_hexagon(pol_21).
not_hexagon(pol_26).
not_hexagon(pol_31).
not_hexagon(pol_36).
not_hexagon(pol_41).
not_hexagon(pol_46).
not_hexagon(pol_51).
not_hexagon(pol_56).
not_hexagon(pol_6).
