right_angle(pol_1).
right_angle(pol_10).
right_angle(pol_11).
right_angle(pol_13).
right_angle(pol_14).
right_angle(pol_15).
right_angle(pol_16).
right_angle(pol_18).
right_angle(pol_19).
right_angle(pol_20).
right_angle(pol_3).
right_angle(pol_4).
right_angle(pol_5).
right_angle(pol_6).
right_angle(pol_8).
right_angle(pol_9).
not_right_angle(pol_21).
not_right_angle(pol_23).
not_right_angle(pol_24).
not_right_angle(pol_25).
not_right_angle(pol_26).
not_right_angle(pol_28).
not_right_angle(pol_29).
not_right_angle(pol_30).
not_right_angle(pol_31).
not_right_angle(pol_33).
not_right_angle(pol_34).
not_right_angle(pol_35).
not_right_angle(pol_36).
not_right_angle(pol_38).
not_right_angle(pol_39).
not_right_angle(pol_40).
