right_angle(pol_1).
right_angle(pol_11).
right_angle(pol_12).
right_angle(pol_13).
right_angle(pol_14).
right_angle(pol_16).
right_angle(pol_17).
right_angle(pol_18).
right_angle(pol_19).
right_angle(pol_2).
right_angle(pol_3).
right_angle(pol_4).
right_angle(pol_6).
right_angle(pol_7).
right_angle(pol_8).
right_angle(pol_9).
not_right_angle(pol_21).
not_right_angle(pol_22).
not_right_angle(pol_23).
not_right_angle(pol_24).
not_right_angle(pol_26).
not_right_angle(pol_27).
not_right_angle(pol_28).
not_right_angle(pol_29).
not_right_angle(pol_31).
not_right_angle(pol_32).
not_right_angle(pol_33).
not_right_angle(pol_34).
not_right_angle(pol_36).
not_right_angle(pol_37).
not_right_angle(pol_38).
not_right_angle(pol_39).
