not(triangle(pol_1)).
not(triangle(pol_2)).
triangle(pol_3).
triangle(pol_4).
triangle(pol_5).
not(triangle(pol_6)).
not(triangle(pol_7)).
triangle(pol_8).
triangle(pol_9).
not(triangle(pol_10)).
not(triangle(pol_11)).
