triangle(pol_14).
triangle(pol_19).
triangle(pol_4).
triangle(pol_9).
not_triangle(pol_24).
not_triangle(pol_29).
not_triangle(pol_34).
not_triangle(pol_39).
not_triangle(pol_44).
not_triangle(pol_49).
not_triangle(pol_54).
not_triangle(pol_59).
not_triangle(pol_64).
not_triangle(pol_69).
not_triangle(pol_74).
not_triangle(pol_79).
quadrangle(pol_24).
quadrangle(pol_29).
quadrangle(pol_34).
quadrangle(pol_39).
not_quadrangle(pol_14).
not_quadrangle(pol_19).
not_quadrangle(pol_4).
not_quadrangle(pol_44).
not_quadrangle(pol_49).
not_quadrangle(pol_54).
not_quadrangle(pol_59).
not_quadrangle(pol_64).
not_quadrangle(pol_69).
not_quadrangle(pol_74).
not_quadrangle(pol_79).
not_quadrangle(pol_9).
pentagon(pol_44).
pentagon(pol_49).
pentagon(pol_54).
pentagon(pol_59).
not_pentagon(pol_14).
not_pentagon(pol_19).
not_pentagon(pol_24).
not_pentagon(pol_29).
not_pentagon(pol_34).
not_pentagon(pol_39).
not_pentagon(pol_4).
not_pentagon(pol_64).
not_pentagon(pol_69).
not_pentagon(pol_74).
not_pentagon(pol_79).
not_pentagon(pol_9).
hexagon(pol_64).
hexagon(pol_69).
hexagon(pol_74).
hexagon(pol_79).
not_hexagon(pol_14).
not_hexagon(pol_19).
not_hexagon(pol_24).
not_hexagon(pol_29).
not_hexagon(pol_34).
not_hexagon(pol_39).
not_hexagon(pol_4).
not_hexagon(pol_44).
not_hexagon(pol_49).
not_hexagon(pol_54).
not_hexagon(pol_59).
not_hexagon(pol_9).
