triangle(pol_1).
triangle(pol_11).
triangle(pol_12).
triangle(pol_13).
triangle(pol_14).
triangle(pol_16).
triangle(pol_17).
triangle(pol_18).
triangle(pol_19).
triangle(pol_2).
triangle(pol_3).
triangle(pol_4).
triangle(pol_6).
triangle(pol_7).
triangle(pol_8).
triangle(pol_9).
not_triangle(pol_21).
not_triangle(pol_22).
not_triangle(pol_23).
not_triangle(pol_24).
not_triangle(pol_26).
not_triangle(pol_27).
not_triangle(pol_28).
not_triangle(pol_29).
not_triangle(pol_31).
not_triangle(pol_32).
not_triangle(pol_33).
not_triangle(pol_34).
not_triangle(pol_36).
not_triangle(pol_37).
not_triangle(pol_38).
not_triangle(pol_39).
not_triangle(pol_41).
not_triangle(pol_42).
not_triangle(pol_43).
not_triangle(pol_44).
not_triangle(pol_46).
not_triangle(pol_47).
not_triangle(pol_48).
not_triangle(pol_49).
not_triangle(pol_51).
not_triangle(pol_52).
not_triangle(pol_53).
not_triangle(pol_54).
not_triangle(pol_56).
not_triangle(pol_57).
not_triangle(pol_58).
not_triangle(pol_59).
not_triangle(pol_61).
not_triangle(pol_62).
not_triangle(pol_63).
not_triangle(pol_64).
not_triangle(pol_66).
not_triangle(pol_67).
not_triangle(pol_68).
not_triangle(pol_69).
not_triangle(pol_71).
not_triangle(pol_72).
not_triangle(pol_73).
not_triangle(pol_74).
not_triangle(pol_76).
not_triangle(pol_77).
not_triangle(pol_78).
not_triangle(pol_79).
quadrangle(pol_21).
quadrangle(pol_22).
quadrangle(pol_23).
quadrangle(pol_24).
quadrangle(pol_26).
quadrangle(pol_27).
quadrangle(pol_28).
quadrangle(pol_29).
quadrangle(pol_31).
quadrangle(pol_32).
quadrangle(pol_33).
quadrangle(pol_34).
quadrangle(pol_36).
quadrangle(pol_37).
quadrangle(pol_38).
quadrangle(pol_39).
not_quadrangle(pol_1).
not_quadrangle(pol_11).
not_quadrangle(pol_12).
not_quadrangle(pol_13).
not_quadrangle(pol_14).
not_quadrangle(pol_16).
not_quadrangle(pol_17).
not_quadrangle(pol_18).
not_quadrangle(pol_19).
not_quadrangle(pol_2).
not_quadrangle(pol_3).
not_quadrangle(pol_4).
not_quadrangle(pol_41).
not_quadrangle(pol_42).
not_quadrangle(pol_43).
not_quadrangle(pol_44).
not_quadrangle(pol_46).
not_quadrangle(pol_47).
not_quadrangle(pol_48).
not_quadrangle(pol_49).
not_quadrangle(pol_51).
not_quadrangle(pol_52).
not_quadrangle(pol_53).
not_quadrangle(pol_54).
not_quadrangle(pol_56).
not_quadrangle(pol_57).
not_quadrangle(pol_58).
not_quadrangle(pol_59).
not_quadrangle(pol_6).
not_quadrangle(pol_61).
not_quadrangle(pol_62).
not_quadrangle(pol_63).
not_quadrangle(pol_64).
not_quadrangle(pol_66).
not_quadrangle(pol_67).
not_quadrangle(pol_68).
not_quadrangle(pol_69).
not_quadrangle(pol_7).
not_quadrangle(pol_71).
not_quadrangle(pol_72).
not_quadrangle(pol_73).
not_quadrangle(pol_74).
not_quadrangle(pol_76).
not_quadrangle(pol_77).
not_quadrangle(pol_78).
not_quadrangle(pol_79).
not_quadrangle(pol_8).
not_quadrangle(pol_9).
pentagon(pol_41).
pentagon(pol_42).
pentagon(pol_43).
pentagon(pol_44).
pentagon(pol_46).
pentagon(pol_47).
pentagon(pol_48).
pentagon(pol_49).
pentagon(pol_51).
pentagon(pol_52).
pentagon(pol_53).
pentagon(pol_54).
pentagon(pol_56).
pentagon(pol_57).
pentagon(pol_58).
pentagon(pol_59).
not_pentagon(pol_1).
not_pentagon(pol_11).
not_pentagon(pol_12).
not_pentagon(pol_13).
not_pentagon(pol_14).
not_pentagon(pol_16).
not_pentagon(pol_17).
not_pentagon(pol_18).
not_pentagon(pol_19).
not_pentagon(pol_2).
not_pentagon(pol_21).
not_pentagon(pol_22).
not_pentagon(pol_23).
not_pentagon(pol_24).
not_pentagon(pol_26).
not_pentagon(pol_27).
not_pentagon(pol_28).
not_pentagon(pol_29).
not_pentagon(pol_3).
not_pentagon(pol_31).
not_pentagon(pol_32).
not_pentagon(pol_33).
not_pentagon(pol_34).
not_pentagon(pol_36).
not_pentagon(pol_37).
not_pentagon(pol_38).
not_pentagon(pol_39).
not_pentagon(pol_4).
not_pentagon(pol_6).
not_pentagon(pol_61).
not_pentagon(pol_62).
not_pentagon(pol_63).
not_pentagon(pol_64).
not_pentagon(pol_66).
not_pentagon(pol_67).
not_pentagon(pol_68).
not_pentagon(pol_69).
not_pentagon(pol_7).
not_pentagon(pol_71).
not_pentagon(pol_72).
not_pentagon(pol_73).
not_pentagon(pol_74).
not_pentagon(pol_76).
not_pentagon(pol_77).
not_pentagon(pol_78).
not_pentagon(pol_79).
not_pentagon(pol_8).
not_pentagon(pol_9).
hexagon(pol_61).
hexagon(pol_62).
hexagon(pol_63).
hexagon(pol_64).
hexagon(pol_66).
hexagon(pol_67).
hexagon(pol_68).
hexagon(pol_69).
hexagon(pol_71).
hexagon(pol_72).
hexagon(pol_73).
hexagon(pol_74).
hexagon(pol_76).
hexagon(pol_77).
hexagon(pol_78).
hexagon(pol_79).
not_hexagon(pol_1).
not_hexagon(pol_11).
not_hexagon(pol_12).
not_hexagon(pol_13).
not_hexagon(pol_14).
not_hexagon(pol_16).
not_hexagon(pol_17).
not_hexagon(pol_18).
not_hexagon(pol_19).
not_hexagon(pol_2).
not_hexagon(pol_21).
not_hexagon(pol_22).
not_hexagon(pol_23).
not_hexagon(pol_24).
not_hexagon(pol_26).
not_hexagon(pol_27).
not_hexagon(pol_28).
not_hexagon(pol_29).
not_hexagon(pol_3).
not_hexagon(pol_31).
not_hexagon(pol_32).
not_hexagon(pol_33).
not_hexagon(pol_34).
not_hexagon(pol_36).
not_hexagon(pol_37).
not_hexagon(pol_38).
not_hexagon(pol_39).
not_hexagon(pol_4).
not_hexagon(pol_41).
not_hexagon(pol_42).
not_hexagon(pol_43).
not_hexagon(pol_44).
not_hexagon(pol_46).
not_hexagon(pol_47).
not_hexagon(pol_48).
not_hexagon(pol_49).
not_hexagon(pol_51).
not_hexagon(pol_52).
not_hexagon(pol_53).
not_hexagon(pol_54).
not_hexagon(pol_56).
not_hexagon(pol_57).
not_hexagon(pol_58).
not_hexagon(pol_59).
not_hexagon(pol_6).
not_hexagon(pol_7).
not_hexagon(pol_8).
not_hexagon(pol_9).
