episode(triangle,
	[
	 [triangle, pol_10],
	 [triangle, pol_12],
	 [triangle, pol_13],
	 [triangle, pol_14],
	 [triangle, pol_15],
	 [triangle, pol_17],
	 [triangle, pol_18],
	 [triangle, pol_19],
	 [triangle, pol_2],
	 [triangle, pol_20],
	 [triangle, pol_3],
	 [triangle, pol_4],
	 [triangle, pol_5],
	 [triangle, pol_7],
	 [triangle, pol_8],
	 [triangle, pol_9]
	],
	[
	 [triangle, pol_22],
	 [triangle, pol_23],
	 [triangle, pol_24],
	 [triangle, pol_25],
	 [triangle, pol_27],
	 [triangle, pol_28],
	 [triangle, pol_29],
	 [triangle, pol_30],
	 [triangle, pol_32],
	 [triangle, pol_33],
	 [triangle, pol_34],
	 [triangle, pol_35],
	 [triangle, pol_37],
	 [triangle, pol_38],
	 [triangle, pol_39],
	 [triangle, pol_40],
	 [triangle, pol_42],
	 [triangle, pol_43],
	 [triangle, pol_44],
	 [triangle, pol_45],
	 [triangle, pol_47],
	 [triangle, pol_48],
	 [triangle, pol_49],
	 [triangle, pol_50],
	 [triangle, pol_52],
	 [triangle, pol_53],
	 [triangle, pol_54],
	 [triangle, pol_55],
	 [triangle, pol_57],
	 [triangle, pol_58],
	 [triangle, pol_59],
	 [triangle, pol_60],
	 [triangle, pol_62],
	 [triangle, pol_63],
	 [triangle, pol_64],
	 [triangle, pol_65],
	 [triangle, pol_67],
	 [triangle, pol_68],
	 [triangle, pol_69],
	 [triangle, pol_70],
	 [triangle, pol_72],
	 [triangle, pol_73],
	 [triangle, pol_74],
	 [triangle, pol_75],
	 [triangle, pol_77],
	 [triangle, pol_78],
	 [triangle, pol_79],
	 [triangle, pol_80]
	]
       ).

episode(quadrangle,
	[
	 [quadrangle, pol_22],
	 [quadrangle, pol_23],
	 [quadrangle, pol_24],
	 [quadrangle, pol_25],
	 [quadrangle, pol_27],
	 [quadrangle, pol_28],
	 [quadrangle, pol_29],
	 [quadrangle, pol_30],
	 [quadrangle, pol_32],
	 [quadrangle, pol_33],
	 [quadrangle, pol_34],
	 [quadrangle, pol_35],
	 [quadrangle, pol_37],
	 [quadrangle, pol_38],
	 [quadrangle, pol_39],
	 [quadrangle, pol_40]
	],
	[
	 [quadrangle, pol_10],
	 [quadrangle, pol_12],
	 [quadrangle, pol_13],
	 [quadrangle, pol_14],
	 [quadrangle, pol_15],
	 [quadrangle, pol_17],
	 [quadrangle, pol_18],
	 [quadrangle, pol_19],
	 [quadrangle, pol_2],
	 [quadrangle, pol_20],
	 [quadrangle, pol_3],
	 [quadrangle, pol_4],
	 [quadrangle, pol_42],
	 [quadrangle, pol_43],
	 [quadrangle, pol_44],
	 [quadrangle, pol_45],
	 [quadrangle, pol_47],
	 [quadrangle, pol_48],
	 [quadrangle, pol_49],
	 [quadrangle, pol_5],
	 [quadrangle, pol_50],
	 [quadrangle, pol_52],
	 [quadrangle, pol_53],
	 [quadrangle, pol_54],
	 [quadrangle, pol_55],
	 [quadrangle, pol_57],
	 [quadrangle, pol_58],
	 [quadrangle, pol_59],
	 [quadrangle, pol_60],
	 [quadrangle, pol_62],
	 [quadrangle, pol_63],
	 [quadrangle, pol_64],
	 [quadrangle, pol_65],
	 [quadrangle, pol_67],
	 [quadrangle, pol_68],
	 [quadrangle, pol_69],
	 [quadrangle, pol_7],
	 [quadrangle, pol_70],
	 [quadrangle, pol_72],
	 [quadrangle, pol_73],
	 [quadrangle, pol_74],
	 [quadrangle, pol_75],
	 [quadrangle, pol_77],
	 [quadrangle, pol_78],
	 [quadrangle, pol_79],
	 [quadrangle, pol_8],
	 [quadrangle, pol_80],
	 [quadrangle, pol_9]
	]
       ).

episode(pentagon,
	[
	 [pentagon, pol_42],
	 [pentagon, pol_43],
	 [pentagon, pol_44],
	 [pentagon, pol_45],
	 [pentagon, pol_47],
	 [pentagon, pol_48],
	 [pentagon, pol_49],
	 [pentagon, pol_50],
	 [pentagon, pol_52],
	 [pentagon, pol_53],
	 [pentagon, pol_54],
	 [pentagon, pol_55],
	 [pentagon, pol_57],
	 [pentagon, pol_58],
	 [pentagon, pol_59],
	 [pentagon, pol_60]
	],
	[
	 [pentagon, pol_10],
	 [pentagon, pol_12],
	 [pentagon, pol_13],
	 [pentagon, pol_14],
	 [pentagon, pol_15],
	 [pentagon, pol_17],
	 [pentagon, pol_18],
	 [pentagon, pol_19],
	 [pentagon, pol_2],
	 [pentagon, pol_20],
	 [pentagon, pol_22],
	 [pentagon, pol_23],
	 [pentagon, pol_24],
	 [pentagon, pol_25],
	 [pentagon, pol_27],
	 [pentagon, pol_28],
	 [pentagon, pol_29],
	 [pentagon, pol_3],
	 [pentagon, pol_30],
	 [pentagon, pol_32],
	 [pentagon, pol_33],
	 [pentagon, pol_34],
	 [pentagon, pol_35],
	 [pentagon, pol_37],
	 [pentagon, pol_38],
	 [pentagon, pol_39],
	 [pentagon, pol_4],
	 [pentagon, pol_40],
	 [pentagon, pol_5],
	 [pentagon, pol_62],
	 [pentagon, pol_63],
	 [pentagon, pol_64],
	 [pentagon, pol_65],
	 [pentagon, pol_67],
	 [pentagon, pol_68],
	 [pentagon, pol_69],
	 [pentagon, pol_7],
	 [pentagon, pol_70],
	 [pentagon, pol_72],
	 [pentagon, pol_73],
	 [pentagon, pol_74],
	 [pentagon, pol_75],
	 [pentagon, pol_77],
	 [pentagon, pol_78],
	 [pentagon, pol_79],
	 [pentagon, pol_8],
	 [pentagon, pol_80],
	 [pentagon, pol_9]
	]
       ).

episode(hexagon,
	[
	 [hexagon, pol_62],
	 [hexagon, pol_63],
	 [hexagon, pol_64],
	 [hexagon, pol_65],
	 [hexagon, pol_67],
	 [hexagon, pol_68],
	 [hexagon, pol_69],
	 [hexagon, pol_70],
	 [hexagon, pol_72],
	 [hexagon, pol_73],
	 [hexagon, pol_74],
	 [hexagon, pol_75],
	 [hexagon, pol_77],
	 [hexagon, pol_78],
	 [hexagon, pol_79],
	 [hexagon, pol_80]
	],
	[
	 [hexagon, pol_10],
	 [hexagon, pol_12],
	 [hexagon, pol_13],
	 [hexagon, pol_14],
	 [hexagon, pol_15],
	 [hexagon, pol_17],
	 [hexagon, pol_18],
	 [hexagon, pol_19],
	 [hexagon, pol_2],
	 [hexagon, pol_20],
	 [hexagon, pol_22],
	 [hexagon, pol_23],
	 [hexagon, pol_24],
	 [hexagon, pol_25],
	 [hexagon, pol_27],
	 [hexagon, pol_28],
	 [hexagon, pol_29],
	 [hexagon, pol_3],
	 [hexagon, pol_30],
	 [hexagon, pol_32],
	 [hexagon, pol_33],
	 [hexagon, pol_34],
	 [hexagon, pol_35],
	 [hexagon, pol_37],
	 [hexagon, pol_38],
	 [hexagon, pol_39],
	 [hexagon, pol_4],
	 [hexagon, pol_40],
	 [hexagon, pol_42],
	 [hexagon, pol_43],
	 [hexagon, pol_44],
	 [hexagon, pol_45],
	 [hexagon, pol_47],
	 [hexagon, pol_48],
	 [hexagon, pol_49],
	 [hexagon, pol_5],
	 [hexagon, pol_50],
	 [hexagon, pol_52],
	 [hexagon, pol_53],
	 [hexagon, pol_54],
	 [hexagon, pol_55],
	 [hexagon, pol_57],
	 [hexagon, pol_58],
	 [hexagon, pol_59],
	 [hexagon, pol_60],
	 [hexagon, pol_7],
	 [hexagon, pol_8],
	 [hexagon, pol_9]
	]
       ).

