regular(pol_1).
regular(pol_10).
regular(pol_11).
regular(pol_12).
regular(pol_13).
regular(pol_15).
regular(pol_16).
regular(pol_17).
regular(pol_18).
regular(pol_2).
regular(pol_20).
regular(pol_3).
regular(pol_5).
regular(pol_6).
regular(pol_7).
regular(pol_8).
not_regular(pol_21).
not_regular(pol_22).
not_regular(pol_23).
not_regular(pol_25).
not_regular(pol_26).
not_regular(pol_27).
not_regular(pol_28).
not_regular(pol_30).
not_regular(pol_31).
not_regular(pol_32).
not_regular(pol_33).
not_regular(pol_35).
not_regular(pol_36).
not_regular(pol_37).
not_regular(pol_38).
not_regular(pol_40).
